version: '3.7'

services:
  rt-chat-service:
    container_name: rt-chat-service
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    volumes:
      - .:/app
    working_dir: /app/server
    ports:
      - "1333:1333"
    environment:
      PORT: "1333"
    tty: true
    restart: always
    command: sh ./bin/api.sh
